networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - main_service
      - comments_service
      - bot
    networks:
      - dev

  main_service:
    build:
      context: .
    depends_on:
      - main_to_do_list_db
      - redis
      - celery
    networks:
      - dev


  comments_service:
    build:
      context: ./comments_service
    depends_on:
      - comments_db
      - redis
    networks:
      - dev

  bot:
    build:
      context: ./bot
    depends_on:
      - main_service
      - comments_service
    networks:
      - dev

  main_to_do_list_db:
    image: postgres:16
    container_name: main_to_do_list_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - main_service/.env-non-dev
    ports:
      - 5432:5432

  comments_db:
    image: postgres:16
    container_name: comments_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - comments_service/.env-non-dev
    ports:
      - 5433:5432

  redis:
    image: redis:7
    container_name: to_do_list_redis

  celery:
    image: to_do_list_celery
    build:
      context: ./main_service
    container_name: to_do_list_celery
    command: >
      sh -c "celery -A main_service.app.celery_tasks.main_celery:celery beat --loglevel=INFO &&
             celery -A main_service.app.celery_tasks.main_celery:celery worker --loglevel=INFO"
    env_file:
      - main_service/.env-non-dev
    depends_on:
      - redis

volumes:
  postgresdata: