"""Initial migration

Revision ID: 68f5b4b7dc61
Revises: db2ad12607a6
Create Date: 2024-09-07 11:38:19.509863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68f5b4b7dc61'
down_revision: Union[str, None] = 'db2ad12607a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['title'])
    op.add_column('users', sa.Column('hashed_password', sa.LargeBinary(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
