"""Initial migration

Revision ID: c07958b7df03
Revises: fcb5d50cc805
Create Date: 2024-09-10 22:23:28.074805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07958b7df03'
down_revision: Union[str, None] = 'fcb5d50cc805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('category_title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['authors_name'], ['users.username'], ),
    sa.ForeignKeyConstraint(['category_title'], ['categories.title'], ),
    sa.PrimaryKeyConstraint('title', 'authors_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
