"""Initial migration

Revision ID: fcb5d50cc805
Revises: cd0d0587fc2c
Create Date: 2024-09-09 21:02:43.361542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb5d50cc805'
down_revision: Union[str, None] = 'cd0d0587fc2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['tg_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'tg_hash')
    # ### end Alembic commands ###
